import {
  BarChart3,
  Ban,
  CalendarClock,
  ClipboardList,
  DatabaseZap,
  FileJson,
  FileText,
  GitBranch,
  Layers,
  Lightbulb,
  RefreshCw,
  Settings,
  ShieldCheck,
  TrendingDown,
  Users
} from "lucide-react";

export const navigation = [
  { title: "平台總覽", subtitle: "治理狀態", path: "/storyboard", icon: Lightbulb },
  { title: "全行風險總覽", subtitle: "主管儀表板", path: "/", icon: BarChart3 },
  { title: "PQC 前期盤點", subtitle: "系統與業務脈絡", path: "/pqc-intake", icon: ClipboardList },
  { title: "HNDL 長期資料風險", subtitle: "現在攔截、未來解密", path: "/hndl", icon: DatabaseZap },
  { title: "供應商準備度", subtitle: "PQC 遷移追蹤", path: "/vendors", icon: ShieldCheck },
  { title: "跨部門待辦", subtitle: "雙向轉譯與補件", path: "/tasks", icon: Users },
  { title: "治理依據追溯", subtitle: "政策依據與應變模擬", path: "/lineage", icon: GitBranch },
  { title: "遷移優先序", subtitle: "風險與可行性", path: "/migration", icon: Layers },
  { title: "加密調整路線圖", subtitle: "加密調整能力", path: "/crypto-agility", icon: RefreshCw },
  { title: "法規時程", subtitle: "監理截止與追蹤", path: "/regulatory", icon: CalendarClock },
  { title: "演算法汰換清單", subtitle: "脆弱演算法追蹤", path: "/sunset", icon: Ban },
  { title: "CBOM 匯出", subtitle: "加密資產線索", path: "/cbom", icon: FileJson },
  { title: "業務衝擊估算", subtitle: "風險轉管理語言", path: "/business-impact", icon: TrendingDown },
  { title: "盤點證據包", subtitle: "會議與稽核附件", path: "/report", icon: FileText },
  { title: "設定", subtitle: "示範資料與規則", path: "/settings", icon: Settings },
];
