import {
  BarChart3,
  Ban,
  CalendarClock,
  ClipboardList,
  DatabaseZap,
  FileJson,
  FileText,
  GitBranch,
  Layers,
  Lightbulb,
  RefreshCw,
  Settings,
  ShieldCheck,
  TrendingDown,
  Users
} from "lucide-react";

export const navigation = [
  { title: "Executive Storyboard", path: "/storyboard", icon: Lightbulb },
  { title: "Dashboard", path: "/", icon: BarChart3 },
  { title: "PQC Intake", path: "/pqc-intake", icon: ClipboardList },
  { title: "HNDL Analysis", path: "/hndl", icon: DatabaseZap },
  { title: "Vendor Readiness", path: "/vendors", icon: ShieldCheck },
  { title: "Cross-functional Tasks", path: "/tasks", icon: Users },
  { title: "Compliance Lineage", path: "/lineage", icon: GitBranch },
  { title: "Migration Priority", path: "/migration", icon: Layers },
  { title: "Crypto-Agility Roadmap", path: "/crypto-agility", icon: RefreshCw },
  { title: "Regulatory Timeline", path: "/regulatory", icon: CalendarClock },
  { title: "Algorithm Sunset", path: "/sunset", icon: Ban },
  { title: "CBOM Export", path: "/cbom", icon: FileJson },
  { title: "Business Impact", path: "/business-impact", icon: TrendingDown },
  { title: "Evidence Pack", path: "/report", icon: FileText },
  { title: "Settings", path: "/settings", icon: Settings },
];
