import {
  BarChart3,
  Ban,
  CalendarClock,
  ClipboardList,
  DatabaseZap,
  FileJson,
  FileText,
  GitBranch,
  Layers,
  Lightbulb,
  RefreshCw,
  Settings,
  ShieldCheck,
  TrendingDown,
  Users
} from "lucide-react";

export const navigation = [
  { title: "Executive Storyboard", subtitle: "主管決策摘要", path: "/storyboard", icon: Lightbulb },
  { title: "Dashboard", subtitle: "總覽儀表板", path: "/", icon: BarChart3 },
  { title: "PQC Intake", subtitle: "系統盤點填報", path: "/pqc-intake", icon: ClipboardList },
  { title: "HNDL Analysis", subtitle: "長期資料風險", path: "/hndl", icon: DatabaseZap },
  { title: "Vendor Readiness", subtitle: "供應商準備度", path: "/vendors", icon: ShieldCheck },
  { title: "Cross-functional Tasks", subtitle: "跨部門任務", path: "/tasks", icon: Users },
  { title: "Compliance Lineage", subtitle: "合規依據鏈", path: "/lineage", icon: GitBranch },
  { title: "Migration Priority", subtitle: "遷移優先序", path: "/migration", icon: Layers },
  { title: "Crypto-Agility Roadmap", subtitle: "加密敏捷路線圖", path: "/crypto-agility", icon: RefreshCw },
  { title: "Regulatory Timeline", subtitle: "法規截止倒數", path: "/regulatory", icon: CalendarClock },
  { title: "Algorithm Sunset", subtitle: "算法日落清單", path: "/sunset", icon: Ban },
  { title: "CBOM Export", subtitle: "加密資產匯出", path: "/cbom", icon: FileJson },
  { title: "Business Impact", subtitle: "業務衝擊估算", path: "/business-impact", icon: TrendingDown },
  { title: "Evidence Pack", subtitle: "稽核證據包", path: "/report", icon: FileText },
  { title: "Settings", subtitle: "設定", path: "/settings", icon: Settings },
];
